pipeline {
    agent any
      stages {
          stage('Check for changes') {
            when {
              anyOf {
                changeset "**/TP_Microservices_Gesion_users/**"
                expression {
                  return currentBuild.number == 1
                }
              }
            }
            stages{
              stage('build'){
                steps{
                  echo 'Build'
                }
              }
              stage('test'){
                steps{
                  echo 'test'
                }
              }
              stage('Docker Build') {   
                  steps{    
                    dir ('TP_Microservices_Gesion_users'){
                      bat 'docker build -t dockrimage/User_Microservice:latest .'
                    }
                  }
                }
            }
          }
        }
}
